name: adscoin.php

on:
  workflow_dispatch:
    inputs:
      gpgsid:
        description: 'Masukkan gpgsid'
        required: true

jobs:
  claim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # sesuaikan dengan kebutuhan

      - name: Run Claim Script
        env:
          GPGSID: ${{ github.event.inputs.gpgsid }}
        run: php adscoin.php
