name: Adscoin Bot

on:
  workflow_dispatch:
    inputs:
      login:
        description: "gpgsid"
        required: true
  workflow_call:
    inputs:
      login:
        required: true
        type: string

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - run: php adscoin/adscoin.php
        env:
          LOGIN: ${{ inputs.login }}