name: Run Captcoin Bot

on:
  workflow_dispatch:
    inputs:
      bot:
        description: 'Pilih bot untuk dijalankan'
        required: true
        type: choice
        options:
          - single.php
          - multi.php
      login:
        description: 'Username'
        required: true
      pass:
        description: 'Password'
        required: true
  workflow_call:
    inputs:
      bot:
        required: true
        type: string
      login:
        required: true
        type: string
      pass:
        required: true
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Set executable permission
        run: chmod +x captcoin/${{ inputs.bot }}

      - name: Run selected bot
        run: php captcoin/${{ inputs.bot }}
        env:
          LOGIN: ${{ inputs.login }}
          PASS: ${{ inputs.pass }}