name: Run Coolfaucet bot

on:
  workflow_dispatch:
    inputs:
      login_method:
        description: 'email'
        required: true
        type: choice
        options:
          - nodejs
          - cookie
      login_value:
        description: 'input cookie atau email(node.js)'
        required: true
        type: string
  workflow_call:
    inputs:
      login_method:
        required: true
        type: string
      login_value:
        required: true
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Puppeteer login
        if: ${{ inputs.login_method == 'nodejs' }}
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - if: ${{ inputs.login_method == 'nodejs' }}
        run: |
          npm install puppeteer
          node <<'EOF'
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          (async () => {
            const email = process.env.FAUCET_LOGIN;
            const browser = await puppeteer.launch({
              headless: true,
              args: ['--no-sandbox','--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.goto('https://coolfaucet.hu/', {waitUntil: 'domcontentloaded', timeout: 0});
            await page.type('input[name="email"]', email);
            await page.click('button[type="submit"]');
            await page.waitForFunction(() => document.body.innerText.includes('Balance:'), {timeout: 60000});
            const cookies = await page.cookies();
            const cookieString = cookies.map(c => `${c.name}=${c.value}`).join('; ');
            fs.writeFileSync('cookie.txt', cookieString);
            await browser.close();
          })();
        env:
          FAUCET_LOGIN: ${{ inputs.login_value }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Save cookie (if provided directly)
        if: ${{ inputs.login_method == 'cookie' }}
        run: echo "${{ inputs.login_value }}" > cookie.txt

      - run: chmod +x coolfaucet/coolfaucet.php
      - run: php coolfaucet/coolfaucet.php