name: Run PHP Bot

on:
  workflow_dispatch:
    inputs:
      COOKIE:
        description: 'Full Cookie'
        required: true
        default: ''

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Set executable permission
        run: chmod +x coolfaucet/coolfaucet.php

      - name: Run PHP Bot
        env:
          COOKIE: ${{ github.event.inputs.COOKIE }}
        run: php coolfaucet/coolfaucet.php
