name: Run Coolfaucet bot

on:
  workflow_dispatch:
    inputs:
      login_method:
        description: 'LOGIN'
        required: true
        type: choice
        options:
          - nodejs
          - cookie
      login_value:
        description: 'input cookie atau email(node.js)'
        required: true
        type: string

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step Node.js login hanya jalan kalo pilih nodejs
      - name: Puppeteer login
        if: ${{ github.event.inputs.login_method == 'nodejs' }}
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - if: ${{ github.event.inputs.login_method == 'nodejs' }}
        run: |
          npm install puppeteer
          node <<'EOF'
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          (async () => {
            const email = process.env.FAUCET_LOGIN;
            const browser = await puppeteer.launch({
              headless: true,
              args: ['--no-sandbox','--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.goto('https://coolfaucet.hu/', {waitUntil: 'domcontentloaded', timeout: 0});
            await page.type('input[name="email"]', email);
            await page.click('button[type="submit"]');
            await page.waitForFunction(() => document.body.innerText.includes('Balance:'), {timeout: 60000});
            const cookies = await page.cookies();
            const cookieString = cookies.map(c => `${c.name}=${c.value}`).join('; ');
            fs.writeFileSync('cookie.txt', cookieString);
            await browser.close();
          })();
        env:
          FAUCET_LOGIN: ${{ github.event.inputs.login_value }}

      # Step PHP bot
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Kalau user pilih cookie, simpan input ke file
      - name: Save cookie (if provided directly)
        if: ${{ github.event.inputs.login_method == 'cookie' }}
        run: echo "${{ github.event.inputs.login_value }}" > cookie.txt

      - name: Set executable permission
        run: chmod +x coolfaucet/coolfaucet.php

      - name: Run PHP Bot
        run: php coolfaucet/coolfaucet.php
