name: ssh+captcoin.php

on:
  workflow_dispatch:
    inputs:
      login:
        description: 'Login bot (user:pass)'
        required: true
      ssh_login:
        description: 'Login ssh (user@host:pass)'
        required: true
      ssh_port_local:
        description: 'Local port (misal 1080)'
        required: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # 3. Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # 4. Setup SSH tunnel
      - name: Start SSH Tunnel
        run: |
          ssh_userhost=$(echo "${{ github.event.inputs.ssh_login }}" | cut -d':' -f1)
          ssh_pass=$(echo "${{ github.event.inputs.ssh_login }}" | cut -d':' -f2-)
          echo "Menjalankan SSH tunnel di port ${{ github.event.inputs.ssh_port_local }}"
          sshpass -p "$ssh_pass" \
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -f -N -D ${{ github.event.inputs.ssh_port_local }} "$ssh_userhost"
          sleep 5

      # 5. Set executable permission
      - name: Set executable permission
        run: chmod +x captcoin/ssh-captcoin.php

      # 6. Start bot
      - name: Run Captcoin.php
        run: php captcoin/ssh-captcoin.php
        env:
          LOGIN: ${{ github.event.inputs.login }}
          SSH_PROXY_PORT: ${{ github.event.inputs.ssh_port_local }}
