name: ZeroFaucet Bot

on:
  workflow_dispatch:
    inputs:
      login:
        description: 'MATRIX (multi account, format: wallet1,wallet2,...)'
        required: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        login: [ ${{ fromJSON('["' + join(split(github.event.inputs.login, ","), '","') + '"]') }} ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli php-curl tesseract-ocr imagemagick

      - name: Run ZeroFaucet bot
        env:
          LOGIN: ${{ matrix.login }}
        run: php zeroFaucet/zeroFaucet.php
