name: ZeroFaucet Bot

on:
  workflow_dispatch:
    inputs:
      login:
        description: 'LOGIN'
        required: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli php-curl tesseract-ocr imagemagick nodejs npm

      - name: Install puppeteer
        run: npm install puppeteer

      - name: Prepare solveRecaptcha.js
        run: |
          cat <<'EOF' > tes/solveRecaptcha.js
          const puppeteer = require('puppeteer');

          async function solveRecaptcha(sitekey, url) {
            const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
            const page = await browser.newPage();
            await page.goto(url, { waitUntil: 'networkidle2' });
            const token = await page.evaluate((sitekey) => {
              return new Promise((resolve) => {
                grecaptcha.ready(function() {
                  grecaptcha.execute(sitekey, { action: 'submit' }).then(resolve);
                });
              });
            }, sitekey);
            console.log(token);
            await browser.close();
          }

          const [sitekey, url] = process.argv.slice(2);
          if (!sitekey || !url) {
            console.error('Usage: node solveRecaptcha.js <sitekey> <url>');
            process.exit(1);
          }

          solveRecaptcha(sitekey, url).catch(console.error);
          EOF

      - name: Run ZeroFaucet
        env:
          LOGIN: ${{ github.event.inputs.login }}
        run: php tes/zerofaucet.php
